version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: expense_postgres
    restart: always
    environment:
      POSTGRES_DB: expense_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: expense_redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: expense_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI

  expense-app:
    build: .
    container_name: expense_app
    restart: always
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expense_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8080:8080"

volumes:
  pgdata:
