apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-db
  template:
    metadata:
      labels:
        app: expense-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: expense_management
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
