apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-rabbitmq
  template:
    metadata:
      labels:
        app: expense-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
