apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-redis
  template:
    metadata:
      labels:
        app: expense-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
